# Generated by Django 5.2.8 on 2025-11-27 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Nave 1 - Lote Experimental', max_length=50)),
                ('tipo_dieta', models.CharField(choices=[('ALGAS', 'Experimental (Base Algas)'), ('CONTROL', 'Control (Alimento Normal)')], max_length=10)),
                ('cantidad_aves_inicial', models.PositiveIntegerField(help_text='Cuántas gallinas iniciaron')),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Saco Alimento Gallina 20kg', max_length=100)),
                ('categoria', models.CharField(choices=[('MP_ALGA_ENTERA', 'Materia Prima: Alga Entera'), ('MP_ALGA_DESHIDRATADA', 'Materia Prima: Alga Deshidratada'), ('MP_ALGA_MICRONIZADA', 'Materia Prima: Alga Micronizada'), ('PT_ALIMENTO', 'Producto Terminado: Alimento Animal'), ('PT_BIOESTIMULANTE', 'Producto Terminado: Bioestimulante')], max_length=30)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad en Kilos o Litros', max_digits=10)),
                ('capacidad_maxima_diaria', models.DecimalField(decimal_places=2, help_text='Capacidad instalada diaria (Kg/L)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDiarioAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now)),
                ('huevos_recolectados', models.PositiveIntegerField()),
                ('huevos_rotos', models.PositiveIntegerField(default=0)),
                ('alimento_consumido_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mortalidad', models.PositiveIntegerField(default=0, help_text='Gallinas muertas hoy')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loteaves')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, help_text='Kilos o Litros producidos', max_digits=10)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.CharField(help_text='Nombre del trabajador', max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
