# Generated by Django 5.2.8 on 2025-11-27 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='capacidad_maxima_diaria',
            field=models.DecimalField(decimal_places=2, help_text='Capacidad instalada diaria (Kg/L)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad en Kilos o Litros', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reportediarioaves',
            name='alimento_consumido_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reporteproduccion',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=2, help_text='Kilos o Litros producidos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
